// =====================================================================
// Energy Ring Remix - shared parameters
// A parametric remix (ground-up rebuild) inspired by the "ENERGY RING
// (ESP32 + WLED)" lamp by DSL Design on MakerWorld (model 2045449).
// All dimensions in millimetres.
//
// Units: the lamp stands on the desk; base z=0 is the OPEN bottom rim
// of the base shell (where the screw-on plate seats), +z is up.
// The cable notch faces theta=270 degrees (-Y, "back" of the lamp).
// =====================================================================

/* ------------------------- global quality ------------------------- */
$fa = 2;
$fs = 0.5;
FN_ROUND   = 160;   // facets for large cylinders
EPS        = 0.01;

/* ---------------------------- the ring ---------------------------- */
ring_od          = 150;    // outer diameter of the ring
ring_rim_w       = 25;     // radial width of the rim (OD to hole)
ring_t           = 24;     // axial thickness (front face to back face)
ring_wall        = 2.0;    // outer / inner rim wall thickness
ring_face_t      = 2.4;    // front/back face flange thickness
win_r_in         = ring_od/2 - ring_rim_w + 5;   // glow window inner radius (55)
win_r_out        = ring_od/2 - 5;                // glow window outer radius (70)
rebate_depth     = 1.4;    // diffuser rebate depth into face flange
rebate_lap       = 2.0;    // how far the rebate ledge overlaps past the window
diffuser_t       = 1.2;    // diffuser plate thickness
diffuser_clr     = 0.30;   // radial clearance of diffuser skirts/rebate
                           // (0.15 test-printed a hair too tight)

led_strip_w      = 10.5;   // channel width for COB WS2812B strip (10 mm typ.)
led_strip_t      = 2.6;    // radial depth allowance for strip + adhesive

// ring-to-base tab
tab_w            = 40.6;   // tab width (chord, along X)
tab_len          = 10.0;   // how far the tab extends below the ring OD
tab_t            = 12.2;   // tab thickness (along ring axis)
wire_d           = 5.6;    // wire channel diameter through tab / walls

// half-joint alignment pins (angles are flip-symmetric about the Y axis:
// theta -> 180-theta maps pins onto sockets, so one STL mates with itself)
pin_angles       = [60, 300];
socket_angles    = [120, 240];
pin_d            = 2.6;
pin_h            = 4.0;
pin_clr          = 0.25;   // radial clearance for sockets
pin_boss_w       = 8;      // local wall thickening around pins
boss_r_in        = 51.2;   // pin boss radial extent (kept slim so the
boss_r_out       = 54.2;   // diffuser can drop past via its scallops)
pin_r_pos        = 52.6;   // pin/socket centre radius

/* ---------------------------- the base ---------------------------- */
base_od          = 92;
base_wall        = 2.4;
base_h           = 34;     // rim (z=0) to top face
base_top_t       = 2.8;    // closed top thickness
slot_len         = tab_w + 0.6;
slot_w           = tab_t + 0.5;
slot_depth       = tab_len + 0.5;
slot_wire_d      = 6.5;    // hole from slot floor into the cavity

// cable notch (feeds a USB plug through, then plugs into the board)
notch_angle      = 270;    // -Y
notch_w          = 14;     // width in the base wall
notch_h          = 9;      // height of the wall part of the notch
plate_notch_w    = 20;     // wider notch in the plate flange (alignment slack)

/* --------------------------- the thread --------------------------- */
// Coarse single-start 45-degree-flank thread, generated by twist
// extrusion. Single start => the seated (fully tightened) orientation
// is unique, which is what lets us clock the cable notches together.
thr_root_r       = 40.0;   // male root radius (minor radius of the rod)
thr_depth        = 1.6;    // radial depth of the thread rib
thr_pitch        = 5.0;    // axial travel per turn (single start => lead)
thr_len          = 7.0;    // engaged thread length (~1.4 turns)
thr_clr          = 0.30;   // radial clearance female-over-male (print fit)
thr_crest_deg    = 12;     // angular width of the flat crest
thr_steps        = 240;    // polygon facets for the thread profile
thr_slices_per_turn = 120; // extrusion slices per full turn

// CLOCK CALIBRATION: if, on your printer, the fully-tightened plate
// notch lands rotated from the base notch, set this (in degrees) to
// compensate and reprint ONLY the plate. Positive values rotate the
// seated notch position counter-clockwise viewed from below the lamp.
plate_clock_adjust = 0;

/* -------------------------- bottom plate -------------------------- */
plate_t          = 3.5;    // flange thickness
plate_boss_wall  = 4.0;    // radial wall of the male thread ring
grip_n           = 24;     // grip scallops around the flange edge
grip_d           = 5;      // scallop cutter diameter
foot_d           = 10.4;   // recess for adhesive rubber feet
foot_depth       = 1.0;
foot_r_pos       = 34;     // radial position of feet recesses

/* ---------------------- ESP32 board mounting ---------------------- */
// Default: ESP32 DevKit (30-pin), board approx 52.5 x 28.5 mm.
esp_l            = 52.5;
esp_w            = 28.5;
esp_clr          = 0.7;    // side clearance in the rails
rail_h           = 7.0;    // total rail height
rail_ledge_z     = 4.5;    // board rests at this height (pin tails hang below)
rail_t           = 3.0;    // rail base thickness
rail_lip         = 1.4;    // lip that hooks over the board edge
zip_slot         = [3.6, 1.8];  // zip-tie slots flanking the rails

/* ----------------------- battery tub options ---------------------- */
// Envelope sizes for common purchased battery boxes, with wiggle room.
// "cube"  = two 2xAA boxes (~58 x 31.5 x 15.5 each) stacked, or one
//           4xAA 2x2 holder (~58 x 32 x 29).
// "flat"  = one 4xAA flat holder (~62 x 58 x 15.5), 4 cells in a row x2.
// "flat8" = two flat 4xAA holders stacked (8 cells -> 12 V pack).
pocket_cube      = [60, 34, 33];
pocket_flat4     = [64, 60, 17.5];
pocket_flat8     = [64, 60, 34];
tub_od_cube      = 92;     // matches the base
tub_od_flat      = 96;     // slightly wider pedestal for the flat packs
tub_top_t        = 3.0;    // tub top plate (this is the "bottom plate" of the base)
tub_wall         = 2.4;
tub_floor_t      = 2.6;
tub_wire_hole_d  = 8;      // centre-ish pass-through for pack leads
door_t           = 2.4;    // sliding battery door thickness
door_clr         = 0.3;
door_ledge       = 3.5;    // floor ledge around the door opening

// optional rocker switch cutout (KCD1-style snap-in: 13.5 x 19.5 mm)
switch_cutout    = true;
switch_w         = 13.5;
switch_h         = 19.5;

/* ------------- "matched" series: original-model dimensions -------- */
// Measured from the original Energy Ring STLs (uploads analyzed with
// cross-section slicing). The original base = tapered shell slipped
// over a chassis cup (gravity fit - the part that stays on the desk).
// The matched series keeps every outside dimension but threads the
// shell onto the chassis with the same clocked thread as series A.
m_shell_h        = 50;     // shell height (rim to top face)
m_shell_od_top   = 86.6;   // outer diameter at the closed top (in use)
m_shell_od_rim   = 95.0;   // outer diameter at the open rim (desk end)
m_shell_wall     = 3.0;
m_shell_top_t    = 3.0;
m_stem_hole_d    = 28.2;   // ring stem hole in the shell top
m_collar_d       = 37;     // reinforcing collar under the top face
m_collar_h       = 10;     // grip depth for the ring stem
m_crush_rib      = 0.35;   // crush ribs in the collar bore (stem grip)
m_usb_notch      = true;   // low cable notch; disable when a panel
                           // jack supplies power instead
m_usb_w          = 11;     // USB hole in the shell wall at notch_angle
m_usb_h          = 7.5;
m_usb_z          = 2.0;    // above the shell rim

// optional dismiss-button hole in the shell wall (12mm panel-mount
// momentary button, wired to a free ESP32 GPIO + GND; WLED short
// press -> Idle preset). Sits above the USB hole at the back.
m_button_hole    = false;
m_button_d       = 12.4;   // 7.3 for PBS-110 mini buttons
m_button_z       = 24;     // above the shell rim
m_button_angle   = 270;    // 90 = front (nicer when a jack takes the back)

// optional panel-mount USB-C power jack (Gebildet-style 12mm chassis
// jack, 2-wire pigtail). Sits high on the back wall, above the
// chassis barrel, so the body and nut have clear interior space.
m_jack_hole      = false;
m_jack_d         = 12.6;
m_jack_z         = 17;     // lowest safe: hole sits just above the
                           // female thread, and the jack body (Ø~14.5)
                           // clears the chassis barrel top (z=9) while
                           // the shell is being screwed on

m_skirt_od       = 96.0;   // chassis skirt (visible ring at the desk)
m_skirt_h        = 9.5;
m_barrel_h       = 9.0;    // threaded barrel above the skirt (was a
                           // 25.5mm slip barrel in the original)
m_floor_t        = 3.0;    // chassis floor carrying the ESP32 rails

// double-sided ring (matched to original ring envelope)
m_ring_od        = 180;    // r 90
m_ring_t         = 40;     // front face to back face
m_rim_wall       = 2.0;    // inner + outer rim wall thickness
m_ring_id        = 116;    // inner rim bore (r 58), as original
m_stem_d         = 27.8;   // stem OD - fits original shell hole too
m_stem_bore      = 20.0;   // wire passage
m_stem_len       = 16.0;
m_boss_d         = 70;     // dome boss between ring and stem
m_boss_len       = 17.5;
m_spoke_n        = 3;      // thin mid-depth spokes tying the rims
m_spoke_w        = 3.0;
m_spoke_t        = 3.0;

// threaded stem: the ring screws into the shell collar. Crest stays
// at the original stem OD, so the threaded ring still push-fits a
// plain (crush-rib or original) shell hole.
stem_thr_root_r  = 12.6;   // root radius; crest = 12.6+1.3 = 13.9 (Ø27.8)
stem_thr_depth   = 1.3;
stem_thr_pitch   = 4.0;    // single start -> deterministic facing
stem_thr_len     = 14.5;   // ~3.6 turns; chamfered tip beyond it
stem_thr_clr     = 0.30;   // same print clearance as the base thread
ring_clock_adjust = 0;     // trims which way the seated ring faces

// stem locknut ("position-anywhere" option): the ring's stem drops
// through shell_free's plain bore, you aim the ring, then this nut
// screws onto the stem from inside the base and clamps it.
nut_od           = 42;
nut_h            = 10;
nut_grip_n       = 16;     // grip scallops
free_bore_d      = 28.6;   // shell_free: stem spins freely
free_collar_h    = 4;      // shallow locating collar (more stem inside)
free_collar_d    = 40;     // wider clamp seat for the nut face

// snap-in diffuser tray (original interface, one per face)
m_dif_face_t     = 1.0;
m_dif_skirt_h    = 10.0;
m_dif_in_w       = [60.0, 62.0];   // inner skirt: [rim OD it slides over, skirt outer r]
m_dif_out_w      = [85.7, 88.0];   // outer skirt: [skirt inner r, rim ID it slides in]
m_dif_bead       = 0.45;   // snap bead proudness (bite = 0.45 - diffuser_clr
                           // = 0.15 per bead, symmetric on both skirts)
m_dif_bead_z     = [3.5, 8.5];     // bead positions down the skirt

/* --------------------------- helpers ------------------------------ */
// 2D slot: full width w, open-ended at the bottom (extends to y=-h),
// rounded top corners at y=+h
module rounded_slot_2d(w, h, r) {
    hull() {
        translate([-w/2 + r, h - r]) circle(r, $fn = 32);
        translate([ w/2 - r, h - r]) circle(r, $fn = 32);
        translate([-w/2, -h]) square([w, EPS]);
    }
}
